### ISSUE TITLE
Add travis-CI support

### ISSUE THREAD

**Issue by biboudis** [strymonas/staged-streams.ocaml#2]
Add Travis CI support that runs all tests by following:

https://github.com/ocaml/ocaml-ci-scripts/blob/bebbd8ac917e9b0d8ab6e85a5ca9de5fe9a4902a/README-travis.md#opam-package-travis-opamsh

**Comment by biboudis** [comment]
@yallop do you have a skeleton yml file for a metaocaml project? 

//edit1: After examining `https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-ocaml.sh` I think, I should copy that script locally and add a new case for the 4.02.1+BER switch, right?

//edit2: After examining (and slowly learning :stuck_out_tongue:) `https://github.com/ocaml/ocaml-ci-scripts/blob/master/ci_opam.ml` it seems that I cannot run, in between`.travis-ocaml.sh` and `ci_opam`, the snippet below, modularly.

``` ocaml
opam switch 4.02.1+BER
eval "opam config env"
```

What do you think @yallop, @avsm? The quick and dirty way is to copy-paste the script files, I suppose.

**Comment by yallop** [comment]
It looks to me like the easiest approaches are either to:
- [add an entry to the matrix in ocaml-dockerfile](https://github.com/ocaml/ocaml-ci-scripts/issues/137#issuecomment-261722271), or
- add a `fork_dockerhub_user` parameter to `.travis-docker.sh` (along the lines of [`fork_user` and `fork_branch`](https://github.com/ocaml/ocaml-ci-scripts/blob/f2ee5d78e9623836cfb6211cfdcb3fb1b5a2f696/.travis-docker.sh#L7-L8)) that allows it to pull images from different accounts on the Docker Hub.

**Comment by biboudis** [comment]
Resolved by changing `.travis-ocaml.sh` for the moment.

Thanks @yallop!
